[constants]
arch = 'mipsel'

[binaries]
c = arch + '-openwrt-linux-gcc'
cpp = arch + '-openwrt-linux-g++'
ar = arch + '-openwrt-linux-gcc-ar'
strip = arch + '-openwrt-linux-strip'
pkgconfig = 'pkg-config'
#exe_wrapper = 'qemu-' + arch + '-static'

[host_machine]
system = 'linux'
cpu_family = 'mips'
cpu = 'mipsel'
endian = 'little'
