#
# Copyright (C) 2022 Auterion AG
#

name: Build .debs
on:
  pull_request:
    types: [opened, synchronize]
  release:
    types: [published]

jobs:
  build-deb:
    strategy:
      matrix:
        arch: [arm64, amd64]
    uses: Auterion/common-workflows/.github/workflows/deb-workflow.yml@main
    with:
      project-name: "mavlink-router"
      architecture: ${{ matrix.arch }}
      versioned-release: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      include-release-body: false
    secrets: inherit

